export const houses = [
  {
    id: 1,
    imgCard: "images/house.jpg",
    alt: "house",
    price: "$459,000",
    beds: "2",
    baths: "2",
    sqft: "1,000",
    address: "1000 Downton St",
    city: "Las Vegas, NV",
    zipCode: "78750",
  },
  {
    id: 2,
    imgCard: "images/house.jpg",
    alt: "house",
    price: "$300,000",
    beds: "2",
    baths: "2",
    sqft: "1,000",
    address: "1000 Downton St",
    city: "Las Vegas, NV",
    zipCode: "78750",
  },
  {
    id: 3,
    imgCard: "images/house.jpg",
    alt: "house",
    price: "$1,259,000",
    beds: "2",
    baths: "2",
    sqft: "1,000",
    address: "1000 Downton St",
    city: "Austin, TX",
    zipCode: "78750",
  },
  {
    id: 4,
    imgCard: "images/house.jpg",
    alt: "house",
    price: "$259,000",
    beds: "2",
    baths: "2",
    sqft: "1,000",
    address: "1000 Downton St",
    city: "Austin, TX",
    zipCode: "78750",
  },
];
